lib/arm/crc32_impl: clang 16 requires "aes", not "crypto"
This fixes the arm64 build with clang 16:

   lib/arm/crc32_impl.h:270:5: error: always_inline function 'vmull_p64'
       requires target feature 'aes', but would be inlined into function
       'clmul_u32' that is compiled without support for 'aes'