lib/arm: simplify by not trying to skip target attributes
As was done in lib/x86/, use the target function attribute even if the
features are available natively, as this has no known downside.

Exception: this cannot be done for plain simd (NEON), since old versions
of clang don't accept the target attribute for it.